-- =====================================================================
-- 05_rag.sql — vector search + chat storage for the n8n workflows
-- Everything here is used ONLY by n8n (service_role key). The browser
-- (anon / signed-in admin) can't call these functions.
-- =====================================================================

-- ============ 1. pgvector: lets Postgres store and compare embeddings ============
create extension if not exists vector with schema extensions;

-- ============ 2. kb_chunks: one row per piece of a document / web page ============
-- Column names (content, metadata, embedding) are what n8n's Supabase Vector Store node expects.
create table public.kb_chunks (
  id         bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  source_id  uuid not null references public.kb_sources(id) on delete cascade,  -- delete source => chunks go too
  content    text not null,
  metadata   jsonb not null default '{}',
  embedding  extensions.vector(1536),   -- OpenAI text-embedding-3-small = 1536 numbers
  created_at timestamptz not null default now()
);
create index kb_chunks_source_idx    on public.kb_chunks (source_id);
create index kb_chunks_metadata_idx  on public.kb_chunks using gin (metadata);
create index kb_chunks_embedding_idx on public.kb_chunks using hnsw (embedding extensions.vector_cosine_ops);

-- n8n only writes content/metadata/embedding, so copy company_id + source_id out of metadata
create function public.kb_chunks_fill_ids() returns trigger
language plpgsql set search_path = '' as $$
begin
  new.company_id := coalesce(new.company_id, (new.metadata->>'company_id')::uuid);
  new.source_id  := coalesce(new.source_id,  (new.metadata->>'source_id')::uuid);
  if new.company_id is null or new.source_id is null then
    raise exception 'kb_chunks metadata must include company_id and source_id';
  end if;
  return new;
end;
$$;
create trigger kb_chunks_fill_ids before insert on public.kb_chunks
  for each row execute function public.kb_chunks_fill_ids();

alter table public.kb_chunks enable row level security;
revoke all on public.kb_chunks from anon;
create policy "admins read kb_chunks" on public.kb_chunks
  for select to authenticated
  using (company_id in (select company_id from public.company_admins where user_id = (select auth.uid())));

-- ============ 3. match_kb_chunks: the semantic search the agent's tool calls ============
-- Refuses to search unless the filter names a company, so one company can never see another's KB.
create function public.match_kb_chunks(
  query_embedding extensions.vector(1536),
  match_count int default 5,
  filter jsonb default '{}'
) returns table (id bigint, content text, metadata jsonb, similarity float)
language sql stable set search_path = '' as $$
  select c.id, c.content, c.metadata,
         1 - (c.embedding operator(extensions.<=>) query_embedding) as similarity
  from public.kb_chunks c
  where filter ? 'company_id'
    and c.metadata @> filter
  order by c.embedding operator(extensions.<=>) query_embedding
  limit match_count;
$$;

-- ============ 4. conversations + messages: chat history and sources used ============
create table public.conversations (
  id              uuid primary key default gen_random_uuid(),
  company_id      uuid not null references public.companies(id) on delete cascade,
  session_id      text not null,          -- random id the website widget keeps per visitor
  campaign_source text,                   -- e.g. utm_source from a campaign link
  started_at      timestamptz not null default now(),
  last_message_at timestamptz not null default now(),
  unique (company_id, session_id)
);

create table public.messages (
  id                bigint generated by default as identity primary key,
  conversation_id   uuid not null references public.conversations(id) on delete cascade,
  role              text not null check (role in ('user','assistant')),
  content           text not null,
  retrieved_sources jsonb not null default '[]',   -- which KB sources the answer used
  guardrail_flag    text,                           -- e.g. 'blocked_topic', 'post_check_replaced'
  created_at        timestamptz not null default now()
);
create index messages_conversation_idx on public.messages (conversation_id, created_at desc);

alter table public.conversations enable row level security;
alter table public.messages      enable row level security;
revoke all on public.conversations, public.messages from anon;
create policy "admins read conversations" on public.conversations
  for select to authenticated
  using (company_id in (select company_id from public.company_admins where user_id = (select auth.uid())));
create policy "admins read messages" on public.messages
  for select to authenticated
  using (conversation_id in (select id from public.conversations where company_id in
         (select company_id from public.company_admins where user_id = (select auth.uid()))));

-- ============ 5. Helper functions n8n calls (one call instead of many nodes) ============

-- Workflow A, start: mark the source "processing", delete its old chunks, return what to ingest.
create function public.start_ingestion(p_source_id uuid) returns jsonb
language plpgsql set search_path = '' as $$
declare v_row public.kb_sources;
begin
  update public.kb_sources
     set status = 'processing', error = null
   where id = p_source_id
  returning * into v_row;
  if v_row.id is null then
    raise exception 'kb source % not found', p_source_id;
  end if;
  delete from public.kb_chunks where source_id = p_source_id;
  return to_jsonb(v_row);
end;
$$;

-- Workflow A, end: mark the source "ready" or "failed".
create function public.finish_ingestion(
  p_source_id uuid, p_status text, p_error text default null, p_pages_indexed int default null
) returns void
language sql set search_path = '' as $$
  update public.kb_sources
     set status        = p_status,
         error         = case when p_status = 'failed' then left(p_error, 500) end,
         pages_indexed = coalesce(p_pages_indexed, pages_indexed),
         indexed_at    = case when p_status = 'ready' then now() else indexed_at end
   where id = p_source_id;
$$;

-- Workflow B, start: find/create the conversation, count recent messages (rate limit),
-- and return the agent's settings, guardrails and the last 10 messages.
create function public.chat_context(
  p_company_id uuid, p_session_id text, p_campaign_source text default null
) returns jsonb
language plpgsql set search_path = '' as $$
declare
  v_conv   uuid;
  v_recent int;
begin
  if not exists (select 1 from public.companies where id = p_company_id) then
    raise exception 'unknown company';
  end if;

  insert into public.conversations (company_id, session_id, campaign_source)
  values (p_company_id, p_session_id, p_campaign_source)
  on conflict (company_id, session_id) do update set last_message_at = now()
  returning id into v_conv;

  select count(*) into v_recent
    from public.messages
   where conversation_id = v_conv and role = 'user'
     and created_at > now() - interval '10 minutes';

  return jsonb_build_object(
    'conversation_id',      v_conv,
    'recent_user_messages', v_recent,
    'agent',      (select to_jsonb(a) - 'company_context_draft'
                     from public.agent_config a where a.company_id = p_company_id),
    'guardrails', (select to_jsonb(g) from public.guardrails g where g.company_id = p_company_id),
    'history',    coalesce((
                    select jsonb_agg(jsonb_build_object('role', h.role, 'content', h.content)
                                     order by h.created_at)
                      from (select role, content, created_at from public.messages
                             where conversation_id = v_conv
                             order by created_at desc limit 10) h), '[]'::jsonb)
  );
end;
$$;

-- Workflow B, end: save the prospect's message and Maya's reply together.
create function public.save_chat_turn(
  p_conversation_id uuid, p_user_message text, p_assistant_message text,
  p_sources jsonb default '[]', p_guardrail_flag text default null
) returns void
language sql set search_path = '' as $$
  insert into public.messages (conversation_id, role, content, created_at)
  values (p_conversation_id, 'user', p_user_message, now());
  insert into public.messages (conversation_id, role, content, retrieved_sources, guardrail_flag, created_at)
  values (p_conversation_id, 'assistant', p_assistant_message, coalesce(p_sources, '[]'::jsonb),
          p_guardrail_flag, now() + interval '1 millisecond');
  update public.conversations set last_message_at = now() where id = p_conversation_id;
$$;

-- ============ 6. Only n8n (service_role) may call these functions ============
revoke execute on function public.match_kb_chunks(extensions.vector, int, jsonb),
                           public.start_ingestion(uuid),
                           public.finish_ingestion(uuid, text, text, int),
                           public.chat_context(uuid, text, text),
                           public.save_chat_turn(uuid, text, text, jsonb, text)
  from public, anon, authenticated;
grant execute on function public.match_kb_chunks(extensions.vector, int, jsonb),
                          public.start_ingestion(uuid),
                          public.finish_ingestion(uuid, text, text, int),
                          public.chat_context(uuid, text, text),
                          public.save_chat_turn(uuid, text, text, jsonb, text)
  to service_role;
